### PR TITLE
Fixed project project references to point to submodule folder

### PR DESCRIPTION
**Pull request by zfields**
Changed `begin()` parameters for best practice (although no-op)
Advanced submodule to follow bluetooth fix

### CODE REVIEW

**Comment by zfields** [comment]
REVIEW ONLY: DO NOT PULL

**Comment by turkycat** [comment]
Guides use LED 5, so we should maintain consistency as much as possible

**Comment by tommykdev** [comment]
Looks good to me.

**Comment by zfields** [comment]
Fixed the led pin; for now... :-)

**Pull request merged**
